fix(validate): validate project definition file suffix
Ensures project definition files end in
.stackhead.yml or .stackhead.yaml

ci: fix env access

diff --git a/.github/workflows/test-cli.yml b/.github/workflows/test-cli.yml
--- a/.github/workflows/test-cli.yml
+++ b/.github/workflows/test-cli.yml
@@ -7,6 +7,9 @@ on:
       - master
       - next
 
+env:
+  STACKHEAD_VERSION: next
+
 jobs:
 
   build:
@@ -47,3 +50,42 @@ jobs:
 
       - name: Test
         run: go test ./...
+
+  test-validation:
+    name: Test validation
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Remove Python 2 and old Ansible 2.9 version
+        run: sudo apt purge python ansible -y
+      - name: Set up Python 3
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+      - name: Install Ansible v2.10.3 (GH actions currently uses 2.9)
+        run: pip install ansible==2.10.3
+      - name: Print Ansible and Python version
+        run: ansible --version && python --version
+      - name: Download StackHead CLI artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: stackhead-cli
+          path: /home/runner/bin
+      - name: Set execution permission on binary
+        run: chmod +x /home/runner/bin/stackhead-cli
+        working-directory: /home/runner/bin
+      - name: Perform validation tests
+        run: |
+          /home/runner/bin/stackhead-cli init --version ${{ env.STACKHEAD_VERSION }} -v
+          git clone --depth=1 --branch ${{ env.STACKHEAD_VERSION }} https://github.com/getstackhead/stackhead.git stackhead_repo
+          /home/runner/bin/stackhead-cli cli validate ./stackhead_repo/schemas/examples/cli-config/valid/cli.yml
+          /home/runner/bin/stackhead-cli module validate ./stackhead_repo/schemas/examples/module-config/valid/container-module.yml
+          /home/runner/bin/stackhead-cli project validate ./stackhead_repo/schemas/examples/project-definition/valid/project.stackhead.yml
+          /home/runner/bin/stackhead-cli project validate ./stackhead_repo/schemas/examples/project-definition/valid/project-secured.stackhead.yaml
+
+          cp ./stackhead_repo/schemas/examples/project-definition/valid/project.stackhead.yml ./stackhead_repo/schemas/examples/project-definition/invalid/project.yml
+          /home/runner/bin/stackhead-cli project validate ./stackhead_repo/schemas/examples/project-definition/invalid/project.yml && returncode=$? || returncode=$?
+          if [ $returncode -eq 0 ]; then
+            echo "File above should not have validated due to invalid file extension!"
+            exit 1
+          fi
